# Generated by Django 4.1.2 on 2022-11-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='summ',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма'),
        ),
    ]
