# Generated by Django 4.1.2 on 2022-11-22 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО клиента')),
                ('telephone', models.CharField(max_length=12, verbose_name='Контакный телефон')),
                ('address', models.CharField(blank=True, max_length=80, null=True, verbose_name='Адрес клиента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Устройство')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='model',
        ),
        migrations.RemoveField(
            model_name='order',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='summ',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.device'),
        ),
    ]
