# Generated by Django 4.1.2 on 2022-11-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customer_device_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='problem',
            field=models.CharField(default=1, max_length=120, verbose_name='Неисправность'),
            preserve_default=False,
        ),
    ]
