# Generated by Django 4.1.2 on 2022-11-20 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_device_remove_order_model_remove_order_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО клиента')),
                ('telephone', models.CharField(max_length=12, verbose_name='Контакный телефон')),
                ('address', models.CharField(blank=True, max_length=80, null=True, verbose_name='Адрес клиента')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
