# Generated by Django 4.1.2 on 2022-11-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_device_model_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='condition',
            field=models.CharField(default=1, max_length=70, verbose_name='Внешний вид'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='kit',
            field=models.CharField(default=1, max_length=50, verbose_name='Комплект'),
            preserve_default=False,
        ),
    ]
